groups:
- name: services
  rules:
  - alert: Digdag
    expr: node_systemd_unit_state{name="digdag.service", state="active"} != 1
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Digdag is not running: {{ $labels.instance }}."
      description: "Digdag is not running: {{ $labels.instance }}."

  - alert: node_exporter
    expr: node_systemd_unit_state{name="node_exporter.service", state="active"} != 1
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "node_exporter is not running: {{ $labels.instance }}."
      description: "node_exporter is not running: {{ $labels.instance }}."

