exporter:
  # Optional network parameters
  listen_address: ':9943'
  metrics_path: /metrics

  # Optional working directory - overridden by parameter '-path.cwd'
  # working_directory: "/path/to/my/project"

  # Default enable/disable of metrics - overridden if not set by parameter '-metric.*'
  enable_crc32_metric: true
  enable_nb_line_metric: false

  # list of patterns to apply - metrics can be enable/disabled for each group
  files:
    - patterns: ["/var/run/reboot-required"]
      enable_crc32_metric: false
      enable_nb_line_metric: false

    - patterns: ["/var/spool/apt-mirror/updated"]
      enable_crc32_metric: false
      enable_nb_line_metric: false
