# listen: Addr and port to listen (required)
listen: "0.0.0.0:60000"

# access_log (optional)
access_log:
  path: "/dev/stdout"
  format: "ltsv"
  fields: ['time', 'time_nsec', 'status', 'size', 'reqtime_nsec', 'backend', 'path', 'query', 'method']

# error_log (required)
error_log:
  path: "/dev/stderr"

# exporters: The path of exporter_proxy and the URL of the destination exporter
exporters:
  node_exporter:
    path: "/node_exporter/metrics"
    url: "http://127.0.0.1:9100/metrics"
  statup_exporter:
    path: "/statup_exporter/metrics"
    url: "http://127.0.0.1:8080/metrics"
